---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - app.web.test
  resources:
  - selfhealingwebs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.web.test
  resources:
  - selfhealingwebs/finalizers
  verbs:
  - update
- apiGroups:
  - app.web.test
  resources:
  - selfhealingwebs/status
  verbs:
  - get
  - patch
  - update
